#!/usr/bin/env node
// Run one named agent through the installed runtime. This is the implementation on every platform;
// dispatch.sh and dispatch.cmd are compatibility wrappers and contain no control logic.
import { spawn, spawnSync } from "node:child_process";
import { existsSync, readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
// A directory literally named "harness" is not proof of a contained layout (the harness-loop
// skill's own repo is named "harness" and is flat) — only the thin root AGENTS.md a contained
// scaffold writes is (HI-055). Require both.
const PROJECT_ROOT = path.basename(ROOT) === "harness" && existsSync(path.join(path.dirname(ROOT), "AGENTS.md"))
  ? path.dirname(ROOT) : ROOT;
const IS_WIN = process.platform === "win32";
const RUNTIME_REFUSAL = /monthly request limit reached|rate limit exceeded|quota exceeded|usage limit reached|temporarily unavailable|PreToolUse hook returned unsupported|hook returned invalid pre-tool-use JSON output/i;

function commandRuns(command, args = ["--version"]) {
  const result = spawnSync(command, args, { cwd: PROJECT_ROOT, stdio: "ignore", shell: IS_WIN });
  return !result.error && result.status === 0;
}

export function selectRuntime(forced = process.env.HARNESS_RUNTIME || "") {
  if (forced && !["kiro", "claude", "codex"].includes(forced)) {
    throw new Error(`unknown HARNESS_RUNTIME=${forced} (expected kiro, claude or codex)`);
  }
  if (forced) return forced;
  if (existsSync(path.join(PROJECT_ROOT, ".kiro", "agents")) && commandRuns("kiro-cli")) return "kiro";
  if (existsSync(path.join(PROJECT_ROOT, ".claude", "agents")) && commandRuns("claude")) return "claude";
  if (existsSync(path.join(PROJECT_ROOT, ".codex", "agents")) && commandRuns("codex")) return "codex";
  throw new Error("no runtime — install kiro-cli, claude or codex, with the matching agents directory");
}

function checkRuntime(runtime) {
  if (runtime === "kiro" && !process.env.KIRO_API_KEY && !commandRuns("kiro-cli", ["whoami"])) {
    throw new Error("no auth — set KIRO_API_KEY or log in first (kiro-cli login)");
  }
  if (runtime === "claude" && !existsSync(path.join(PROJECT_ROOT, ".claude", "agents"))) {
    throw new Error("runtime=claude but .claude/agents/ is missing");
  }
  if (runtime === "codex") {
    if (!existsSync(path.join(PROJECT_ROOT, ".codex", "hooks.json"))) {
      throw new Error("runtime=codex but .codex/hooks.json is missing — write restrictions would not be enforced");
    }
    if (!commandRuns("codex", ["login", "status"])) throw new Error("codex is not logged in (codex login)");
  }
}

function invocation(runtime, agent, message) {
  if (runtime === "kiro") return [process.execPath, [path.join(ROOT, "tools", "kiro-acp-dispatch.mjs"), agent, message]];
  if (runtime === "claude") return ["claude", ["-p", message, "--agent", agent, "--dangerously-skip-permissions"]];
  return [process.execPath, [path.join(ROOT, "tools", "codex-dispatch.mjs"), agent, message]];
}

// `env` carries the parallel-iteration identity: HARNESS_FEATURE + HARNESS_SLICE tell
// tools/guard-write.mjs which slice of a work-split plan this worker is confined to. It has to
// travel in the environment rather than the prompt, because the prompt is the layer that degrades
// and the guard runs before the model gets a say.
export async function dispatch(agent, message, { runtime = selectRuntime(), env = {} } = {}) {
  checkRuntime(runtime);
  const [command, args] = invocation(runtime, agent, message);
  return await new Promise((resolve, reject) => {
    const child = spawn(command, args, {
      cwd: PROJECT_ROOT, env: { ...process.env, HARNESS_AGENT: agent, ...env }, shell: IS_WIN,
      stdio: ["ignore", "pipe", "pipe"],
    });
    let output = "";
    for (const [stream, sink] of [[child.stdout, process.stdout], [child.stderr, process.stderr]]) {
      stream.on("data", (chunk) => { output += chunk; sink.write(chunk); });
    }
    child.on("error", reject);
    child.on("close", (code, signal) => {
      if (RUNTIME_REFUSAL.test(output)) {
        console.error("runtime refused the dispatch despite its process status; no agent work is accepted");
        return resolve(75);
      }
      resolve(code ?? (signal ? 1 : 0));
    });
  });
}

function agentExists(agent) {
  const manifest = JSON.parse(readFileSync(path.join(ROOT, "agents.manifest.json"), "utf8"));
  return (manifest.agents || []).some((item) => item.name === agent);
}

// One slice of a work-split plan, as its own dispatch. The brief is generated by the code node
// rather than written by the caller: a hand-typed brief is how a worker ends up with a question it
// cannot ask (tools/work-split.mjs).
function sliceBrief(feature, slice) {
  const result = spawnSync(process.execPath, [path.join(ROOT, "tools", "work-split.mjs"), "brief", feature, slice],
    { cwd: ROOT, encoding: "utf8" });
  if (result.status !== 0) {
    console.error(result.stderr || `could not build the brief for ${feature}/${slice}`);
    process.exit(result.status || 1);
  }
  return result.stdout;
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const argv = process.argv.slice(2);
  const flag = (name) => { const i = argv.indexOf(name); return i >= 0 ? argv[i + 1] : null; };
  const feature = flag("--feature"), slice = flag("--slice");
  const positional = argv.filter((value, index) =>
    !value.startsWith("--") && argv[index - 1] !== "--feature" && argv[index - 1] !== "--slice");
  const [agent, ...messageParts] = positional;
  if (slice && !feature) {
    console.error("--slice needs --feature: the slice's allowed paths live in that feature's work-split plan");
    process.exit(2);
  }
  if (!agent || (!messageParts.length && !slice)) {
    console.error("usage: node loop/dispatch.mjs <agent> \"<message>\"\n" +
      "       node loop/dispatch.mjs maker --feature <feat-id> --slice <slice-id>");
    process.exit(2);
  }
  if (!agentExists(agent)) {
    console.error(`no agent "${agent}" in agents.manifest.json`);
    process.exit(2);
  }
  try {
    const runtime = selectRuntime();
    const message = slice ? `${sliceBrief(feature, slice)}\n${messageParts.join(" ")}` : messageParts.join(" ");
    const env = slice ? { HARNESS_FEATURE: feature, HARNESS_SLICE: slice } : {};
    console.log(`runtime: ${runtime} — dispatching ${agent}${slice ? ` on slice ${feature}/${slice}` : ""}`);
    process.exitCode = await dispatch(agent, message, { runtime, env });
  } catch (error) {
    console.error(error.message);
    process.exitCode = 1;
  }
}
