#!/usr/bin/env node
// feature-digest.mjs — a one-line-per-feature index of feature_list.json.
//
// Why: the full list is the single largest thing every agent auto-loads, and it grows with the
// project — 45 features was already 667 lines, dominating the middle of every agent's context
// where recall is worst (references/llm-failure-modes.md). But no agent needs every field of
// every feature up front. It needs to know what exists, what is eligible, and what is waiting —
// then open the real entry for the one feature it is working on.
//
// So the digest goes in `resources` (always loaded, ~1 line per feature) and feature_list.json
// stays the single source of truth, read on demand. Regenerated by init.sh; verify-harness
// reports it stale if it drifts.
//
// Usage: node feature-digest.mjs --target DIR [--check]
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

const args = process.argv.slice(2);
const opt = (n, d = null) => { const i = args.indexOf(n); return i >= 0 ? args[i + 1] : d; };
const CHECK = args.includes("--check");
const TARGET = path.resolve(opt("--target", "."));
const SRC = path.join(TARGET, "feature_list.json");
const OUT = path.join(TARGET, "feature_list.digest.md");

let fl;
try { fl = JSON.parse(readFileSync(SRC, "utf8")); } catch { process.exit(0); }
const features = fl.features || [];

const done = new Set(features.filter((f) => ["done", "passing"].includes(String(f.status || f.state))).map((f) => f.id));
const marker = (f) => {
  const n = String(f.checkerNotes || "").trim();
  if (n.startsWith("NEEDS DESIGN:")) return " [NEEDS DESIGN]";
  if (n.startsWith("NEEDS RE-PLAN:")) return " [NEEDS RE-PLAN]";
  return "";
};
const eligible = (f) =>
  String(f.status || f.state) === "not-started" &&
  (f.dependencies || []).every((d) => done.has(d)) && !marker(f);

const counts = {};
for (const f of features) counts[f.status || f.state] = (counts[f.status || f.state] || 0) + 1;

const rows = features.map((f) => {
  const st = String(f.status || f.state);
  const deps = (f.dependencies || []).length ? ` ← ${(f.dependencies || []).join(",")}` : "";
  const flag = eligible(f) ? " **ELIGIBLE**" : marker(f);
  const att = (f.attempts || 0) ? ` (${f.attempts}/${f.maxAttempts || 3})` : "";
  return `- \`${f.id}\` **${st}**${att}${flag} — ${String(f.name || "").slice(0, 80)}${deps}`;
});

const body = [
  "# Feature digest — generated, do not edit",
  "",
  "One line per feature so an agent can see the whole shape cheaply. **`feature_list.json` remains",
  "the source of truth** — open it for the full entry (behavior, verification, evidence,",
  "checkerNotes) of the feature you are actually working on.",
  "",
  `Regenerated by \`init.sh\`. ${features.length} features — ` +
    Object.entries(counts).map(([k, v]) => `${k}: ${v}`).join(", "),
  "",
  ...rows,
  "",
].join("\n");

if (CHECK) {
  let cur = ""; try { cur = readFileSync(OUT, "utf8"); } catch { /* missing */ }
  process.exit(cur.trim() === body.trim() ? 0 : 1);
}
writeFileSync(OUT, body);
console.log(`feature_list.digest.md: ${features.length} features, ${body.split("\n").length} lines ` +
  `(feature_list.json is ${readFileSync(SRC, "utf8").split("\n").length})`);
